name: Readme Universal Updater

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["*"]
    types:
      - push

jobs:
  run_python_script:
    if: github.event_name == 'push' 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Print secret
      run: echo ${{ secrets.MY_SECRET }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      env:
        API_SECRET: ${{ secrets.API_SECRET }}
      run: |
        python main.py
